- hosts: all
  become: true
  tasks: 
     - name: check current server ip
       command: sudo hostname -I
     - name: check working dir
       command: sudo pwd
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/Deployment.yml
    #  - name: create new service
    #    command: kubectl apply -f /home/ubuntu/Service.yml